server:
    port: 9090

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/darkuriah/segprev-server-testwin-config        
---
#                    uri: https://github.com/darkuriah/segprev-server-testlinux-config
#                    uri: https://github.com/darkuriah/segprev-server-prod-config